server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://xxxx:3306/redis_mq?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: xxxx
    port: 6379
    password: 
    database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
