server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.25.218.185:3306/redis_mq?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Pm,189889386
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 120.25.218.185
    port: 6379
    password: pm,189889386
    database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
